package form_hotel;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import project.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class adminHome extends javax.swing.JFrame {

    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
        txt_tenKhachHang.setEditable(false);
        txt_Sdt.setEditable(false);
        txt_ngayNhanPhong.setEditable(false);
        txt_ngayTraPhong.setEditable(false);
        txt_Email.setEditable(false);
        txt_Gia.setEditable(false);
        txt_soNgayO.setEditable(false);
        txt_tongTien.setEditable(false);
    }
    int id = 0;
    String Query;
    String roomType;
    String bed;
    String roomNumber;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        pn_quanLyTaiKhoanKH = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_searchAccount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_taiKhoanUser = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        lb_ThoatTab1 = new javax.swing.JLabel();
        lb_anhNen = new javax.swing.JLabel();
        pn_quanLyPhong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_soPhong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_phongDon = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_kieuGiuong = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_menhGia = new javax.swing.JTextField();
        btn_themPhong = new javax.swing.JButton();
        btn_suaPhong = new javax.swing.JButton();
        btn_xoaPhong = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_linkAnh = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_danhSachPhong = new javax.swing.JTable();
        lb_thoatTab2 = new javax.swing.JLabel();
        lb_anhNen1 = new javax.swing.JLabel();
        pn_hoaDon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_hoaDon = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txt_tenKhachHang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Sdt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_soNgayO = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Gia = new javax.swing.JTextField();
        txt_ngayNhanPhong = new javax.swing.JTextField();
        txt_tongTien = new javax.swing.JTextField();
        txt_ngayTraPhong = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lb_Search = new javax.swing.JLabel();
        txt_Search = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        lb_ThoatTab3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lb_anhNen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_quanLyTaiKhoanKH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\src\\img\\DX.png")); // NOI18N
        jButton1.setText(" Đăng xuất ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pn_quanLyTaiKhoanKH.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 130, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tìm kiếm theo tên hoặc Email");
        pn_quanLyTaiKhoanKH.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 250, 30));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tìm kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pn_quanLyTaiKhoanKH.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 140, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 102));
        jButton4.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pn_quanLyTaiKhoanKH.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 130, -1));

        txt_searchAccount.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        txt_searchAccount.setForeground(new java.awt.Color(255, 0, 102));
        pn_quanLyTaiKhoanKH.add(txt_searchAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 270, 30));

        tb_taiKhoanUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ & tên", "Email", "Câu hỏi bảo mật", "Địa chỉ", "Trạng thái"
            }
        ));
        tb_taiKhoanUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_taiKhoanUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_taiKhoanUser);

        pn_quanLyTaiKhoanKH.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 830, 460));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        jLabel21.setText("Khách Sạn Hương Ngọc Thảo");
        pn_quanLyTaiKhoanKH.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 370, 70));

        lb_ThoatTab1.setBackground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab1.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_ThoatTab1.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab1.setText("x");
        lb_ThoatTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatTab1MouseClicked(evt);
            }
        });
        pn_quanLyTaiKhoanKH.add(lb_ThoatTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 40));

        lb_anhNen.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\qtv_1.jpg")); // NOI18N
        pn_quanLyTaiKhoanKH.add(lb_anhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("Quản lý tài khoản khách hàng", pn_quanLyTaiKhoanKH);

        pn_quanLyPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Số phòng *");
        pn_quanLyPhong.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 250, 30));

        txt_soPhong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pn_quanLyPhong.add(txt_soPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 250, 24));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Loại phòng *");
        pn_quanLyPhong.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 250, 30));

        cb_phongDon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_phongDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng đơn", "Phòng đôi", "Phòng Vip" }));
        pn_quanLyPhong.add(cb_phongDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 250, 24));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loại giường *");
        pn_quanLyPhong.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 250, 30));

        cb_kieuGiuong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_kieuGiuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi", "Giường Vip" }));
        pn_quanLyPhong.add(cb_kieuGiuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 250, 24));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giá / ngày *");
        pn_quanLyPhong.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 250, 30));

        txt_menhGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pn_quanLyPhong.add(txt_menhGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 250, 24));

        btn_themPhong.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_themPhong.setText("Thêm phòng");
        btn_themPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themPhongActionPerformed(evt);
            }
        });
        pn_quanLyPhong.add(btn_themPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 110, 24));

        btn_suaPhong.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_suaPhong.setText("sửa phòng");
        btn_suaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaPhongActionPerformed(evt);
            }
        });
        pn_quanLyPhong.add(btn_suaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 110, 24));

        btn_xoaPhong.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_xoaPhong.setText("xóa phòng");
        btn_xoaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaPhongActionPerformed(evt);
            }
        });
        pn_quanLyPhong.add(btn_xoaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 110, 24));

        txt_search.setForeground(new java.awt.Color(255, 0, 51));
        txt_search.setBorder(null);
        pn_quanLyPhong.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Link ảnh *");
        pn_quanLyPhong.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 120, 30));
        pn_quanLyPhong.add(txt_linkAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 250, 24));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\search_24px.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 30));

        pn_quanLyPhong.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 102));
        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        jLabel22.setText("Khách Sạn Hương Ngọc Thảo");
        pn_quanLyPhong.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 380, -1));

        tb_danhSachPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Giường", "Giá", "hình ảnh", "Trạng thái"
            }
        ));
        tb_danhSachPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_danhSachPhongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_danhSachPhong);

        pn_quanLyPhong.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 510, 460));

        lb_thoatTab2.setBackground(new java.awt.Color(255, 255, 255));
        lb_thoatTab2.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_thoatTab2.setForeground(new java.awt.Color(255, 255, 255));
        lb_thoatTab2.setText("x");
        lb_thoatTab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_thoatTab2MouseClicked(evt);
            }
        });
        pn_quanLyPhong.add(lb_thoatTab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 40));

        lb_anhNen1.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\qtv_1.jpg")); // NOI18N
        pn_quanLyPhong.add(lb_anhNen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("Quản lý phòng", pn_quanLyPhong);

        pn_hoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_hoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ID", "Họ & tên", "SĐT", "Quốc tịch", "Giới tính", "Email", "Mã CMND", "Địa chỉ", "Ngày nhận phòng ", "Số phòng", "Giường", "Loại phòng", "Giá / ngày"
            }
        ));
        jScrollPane2.setViewportView(tb_hoaDon);

        pn_hoaDon.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 940, 320));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên khách hàng *");
        pn_hoaDon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, -1));

        txt_tenKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_tenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenKhachHangActionPerformed(evt);
            }
        });
        pn_hoaDon.add(txt_tenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ngày nhận phòng *");
        pn_hoaDon.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 200, -1));

        txt_Sdt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pn_hoaDon.add(txt_Sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 200, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ngày trả phòng *");
        pn_hoaDon.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 200, -1));

        txt_soNgayO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_soNgayO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soNgayOActionPerformed(evt);
            }
        });
        pn_hoaDon.add(txt_soNgayO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 200, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Số điện thoại *");
        pn_hoaDon.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 200, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Giá mỗi ngày *");
        pn_hoaDon.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 200, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Số ngày ở *");
        pn_hoaDon.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 200, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tổng số tiền *");
        pn_hoaDon.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 200, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Emai *");
        pn_hoaDon.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        txt_Email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pn_hoaDon.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, -1));

        txt_Gia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pn_hoaDon.add(txt_Gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, -1));

        txt_ngayNhanPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pn_hoaDon.add(txt_ngayNhanPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 200, -1));

        txt_tongTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pn_hoaDon.add(txt_tongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 200, -1));

        txt_ngayTraPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pn_hoaDon.add(txt_ngayTraPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 200, -1));

        jButton8.setBackground(new java.awt.Color(0, 204, 204));
        jButton8.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Làm Mới");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pn_hoaDon.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Search.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\search_24px.png")); // NOI18N
        lb_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SearchMouseClicked(evt);
            }
        });
        jPanel5.add(lb_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 30));

        txt_Search.setForeground(new java.awt.Color(255, 0, 51));
        txt_Search.setBorder(null);
        jPanel5.add(txt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 30));

        pn_hoaDon.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 310, 30));

        jButton9.setBackground(new java.awt.Color(255, 0, 102));
        jButton9.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Thanh Toán");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pn_hoaDon.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 310, 130, 30));

        lb_ThoatTab3.setBackground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab3.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_ThoatTab3.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab3.setText("x");
        lb_ThoatTab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatTab3MouseClicked(evt);
            }
        });
        pn_hoaDon.add(lb_ThoatTab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 40));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 102));
        jLabel23.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        jLabel23.setText("Khách Sạn Hương Ngọc Thảo");
        pn_hoaDon.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, 350, 70));

        lb_anhNen2.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\qtv_1.jpg")); // NOI18N
        pn_hoaDon.add(lb_anhNen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("Quản lý hóa đơn", pn_hoaDon);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void showRoom() {
        ResultSet rs = Select.getData("select * from room");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void showBill() {
        ResultSet rs = Select.getData("select * from customer where checkout is NULL");
        DefaultTableModel model = (DefaultTableModel) tb_hoaDon.getModel();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("select * from users");
        DefaultTableModel model = (DefaultTableModel) tb_taiKhoanUser.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(4), rs.getString(6), rs.getString(7)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        showRoom();
        showBill();
    }//GEN-LAST:event_formComponentShown

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        String search = txt_search.getText();
        ResultSet rs = Select.getData("select * from room where roomNumber = '" + search + "' or roomType like '" + search + "''%' ");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btn_xoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaPhongActionPerformed
        // TODO add your handling code here:
        String roomNumber = txt_soPhong.getText();
        String roomType = (String) cb_phongDon.getSelectedItem();
        String bed = (String) cb_kieuGiuong.getSelectedItem();
        String price = txt_menhGia.getText();
        InsertUpdateDelete.setData("delete from room where roomNumber = '" + roomNumber + "'", "Cập nhật thành công");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        model.setRowCount(0);
        showRoom();
    }//GEN-LAST:event_btn_xoaPhongActionPerformed

    private void btn_suaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaPhongActionPerformed
        // TODO add your handling code here:
        String roomNumber = txt_soPhong.getText();
        String imgUrl = txt_linkAnh.getText();
        String roomType = (String) cb_phongDon.getSelectedItem();
        String bed = (String) cb_kieuGiuong.getSelectedItem();
        String price = txt_menhGia.getText();
        InsertUpdateDelete.setData("update room set roomType = '" + roomType + "', bed = '" + bed + "', price = '" + price + "', imgUrl = '" + imgUrl + "' where roomNumber = '" + roomNumber + "'", "Cập nhật thành công");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        model.setRowCount(0);
        showRoom();

    }//GEN-LAST:event_btn_suaPhongActionPerformed

    private void btn_themPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themPhongActionPerformed
        String imgUrl = txt_linkAnh.getText();
        String roomNumber = txt_soPhong.getText();
        String roomType = (String) cb_phongDon.getSelectedItem();
        String bed = (String) cb_kieuGiuong.getSelectedItem();
        String price = txt_menhGia.getText();
        String Query = "insert into room values ('" + roomNumber + "', '" + roomType + "','" + bed + "','" + price + "','" + imgUrl + "','Hoạt động' )";
        InsertUpdateDelete.setData(Query, "Thêm phòng thành công");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        model.setRowCount(0);
        showRoom();

    }//GEN-LAST:event_btn_themPhongActionPerformed

    private void tb_taiKhoanUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_taiKhoanUserMouseClicked
        // TODO add your handling code here:
        int index = tb_taiKhoanUser.getSelectedRow();
        TableModel model = tb_taiKhoanUser.getModel();
        String email = model.getValueAt(index, 1).toString();
        String status = model.getValueAt(index, 4).toString();
        if (status.equals("true")) {
            status = "false";
        } else {
            status = "true";
        }
        try {
            int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thay đổi trạng thái của " + email + "", "Select", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                InsertUpdateDelete.setData("update users set status = '" + status + "' where email = '" + email + "'", "Thay đổi trạng thái thành công");
                setVisible(false);
                new adminHome().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tb_taiKhoanUserMouseClicked

    private void tb_danhSachPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_danhSachPhongMouseClicked
        // TODO add your handling code here:
        int row = tb_danhSachPhong.getSelectedRow();
        String RoomNumber = tb_danhSachPhong.getValueAt(row, 0).toString();
        String TypeRoom = tb_danhSachPhong.getValueAt(row, 1).toString();
        String Bed = tb_danhSachPhong.getValueAt(row, 2).toString();
        String Price = tb_danhSachPhong.getValueAt(row, 3).toString();
        String imgUrl = tb_danhSachPhong.getValueAt(row, 4).toString();
        txt_soPhong.setText(RoomNumber);
        int i = 0;
        while (true) {
            String nameFromCbB = cb_phongDon.getItemAt(i).toString();
            if (nameFromCbB.equalsIgnoreCase(TypeRoom)) {
                cb_phongDon.setSelectedIndex(i);
                break;
            }
            i++;
        }
        while (true) {
            String nameFromCbB = cb_kieuGiuong.getItemAt(i).toString();
            if (nameFromCbB.equalsIgnoreCase(Bed)) {
                cb_kieuGiuong.setSelectedIndex(i);
                break;
            }
            i++;
        }
        txt_menhGia.setText(Price);
        txt_linkAnh.setText(imgUrl);
    }//GEN-LAST:event_tb_danhSachPhongMouseClicked

    private void txt_tenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenKhachHangActionPerformed

    private void txt_soNgayOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soNgayOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soNgayOActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        setVisible(false);
//        new customerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void lb_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SearchMouseClicked
        // TODO add your handling code here:
        String Search = txt_Search.getText();
        try {
            ResultSet rs = Select.getData("select * from customer where roomNumber ='" + Search + "' and checkout is NULL");
            if (rs.next()) {
                id = rs.getInt(1);
                txt_tenKhachHang.setText(rs.getString(2));
                txt_ngayNhanPhong.setText(rs.getString(9));
                txt_Sdt.setText(rs.getString(3));
                txt_Gia.setText(rs.getString(13));

                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal = Calendar.getInstance();
                txt_ngayTraPhong.setText(myFormat.format(cal.getTime()));
                String dateBeforeString = rs.getString(9);
                java.util.Date dateBefor = myFormat.parse(dateBeforeString);
                String dateAfterString = myFormat.format(cal.getTime());
                java.util.Date dateAfter = myFormat.parse(dateAfterString);
                long difference = dateAfter.getTime() - dateBefor.getTime();
                int noOfDayStay = (int) (difference / (1000 * 60 * 60 * 24));
                if (noOfDayStay == 0) {
                    noOfDayStay = 1;
                }
                txt_soNgayO.setText(String.valueOf(noOfDayStay));
                float price = Float.parseFloat(txt_Gia.getText());

                txt_tongTien.setText(String.valueOf(noOfDayStay * price));
                txt_Email.setText(rs.getString(6));
                roomType = rs.getString(12);
                bed = rs.getString(11);
            } else {
                JOptionPane.showMessageDialog(null, "Số phòng chưa được đặt trước hoặc số phòng không tồn tại !");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lb_SearchMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String name = txt_tenKhachHang.getText();
        String PhoneNumber = txt_Sdt.getText();
        String email = txt_Email.getText();
        String checkout = txt_ngayTraPhong.getText();
        String numberOfDaysStay = txt_soNgayO.getText();
        String totalAmount = txt_tongTien.getText();
        roomNumber = txt_tenKhachHang.getText();
        Query = "update customer set numberDaysStay = '" + numberOfDaysStay + "' , totalAmount = '" + totalAmount + "', checkout = '" + checkout + "' where id = '" + id + "'";
        InsertUpdateDelete.setData(Query, "");
        Query = "update room set Status = 'Hoạt động' where roomNumber = '" + roomNumber + "'";
        InsertUpdateDelete.setData(Query, "");
        String path = "D:\\Workspace\\Java application\\Hotel Management System\\In hóa đơn\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "Hóa đơn " + id + ".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                          Huong Ngoc Thao Hotel \\n ");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("****************************************************************************************************************");
            doc.add(paragraph2);
            Paragraph paragraph3 = new Paragraph("\t Id Bill : " + id + "\nInformation Customer. \n Full Name : " + name + "\n Phone Number : " + PhoneNumber + "\nEmail : " + email + "\n  ");
            doc.add(paragraph3);
            doc.add(paragraph2);
            Paragraph paragraph4 = new Paragraph("\t Information Room. \n Room Number " + txt_Search.getText() + "\n Type room : " + roomType + "\n Bed : " + bed + "\n price per day : " + txt_Gia.getText() + "");
            doc.add(paragraph4);
            doc.add(paragraph2);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("check-in date : " + txt_ngayNhanPhong.getText());
            tb1.addCell("check-out date : " + checkout);
            tb1.addCell("number of days in : " + numberOfDaysStay);
            tb1.addCell("Total amount : " + totalAmount);
            doc.add(tb1);
            doc.add(paragraph2);
            Paragraph paragraph5 = new Paragraph("Thank you guest ,See you next time !");
            doc.add(paragraph5);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn in hóa đơn ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                if ((new File("D:\\Workspace\\Java application\\Hotel Management System\\In hóa đơn\\Hóa đơn " + id + ".pdf")).exists()) {
                    JOptionPane.showMessageDialog(null, "In hóa đơn thành công");
                } else {
                    System.out.println("Tập tin không tồn tại ");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        setVisible(false);
        new adminHome().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void lb_ThoatTab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatTab1MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            System.exit(a);
        }
    }//GEN-LAST:event_lb_ThoatTab1MouseClicked

    private void lb_thoatTab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_thoatTab2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            System.exit(a);
        }
    }//GEN-LAST:event_lb_thoatTab2MouseClicked

    private void lb_ThoatTab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatTab3MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            System.exit(a);
        }
    }//GEN-LAST:event_lb_ThoatTab3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suaPhong;
    private javax.swing.JButton btn_themPhong;
    private javax.swing.JButton btn_xoaPhong;
    private javax.swing.JComboBox<String> cb_kieuGiuong;
    private javax.swing.JComboBox<String> cb_phongDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lb_Search;
    private javax.swing.JLabel lb_ThoatTab1;
    private javax.swing.JLabel lb_ThoatTab3;
    private javax.swing.JLabel lb_anhNen;
    private javax.swing.JLabel lb_anhNen1;
    private javax.swing.JLabel lb_anhNen2;
    private javax.swing.JLabel lb_thoatTab2;
    private javax.swing.JPanel pn_hoaDon;
    private javax.swing.JPanel pn_quanLyPhong;
    private javax.swing.JPanel pn_quanLyTaiKhoanKH;
    private javax.swing.JTable tb_danhSachPhong;
    private javax.swing.JTable tb_hoaDon;
    private javax.swing.JTable tb_taiKhoanUser;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Gia;
    private javax.swing.JTextField txt_Sdt;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_linkAnh;
    private javax.swing.JTextField txt_menhGia;
    private javax.swing.JTextField txt_ngayNhanPhong;
    private javax.swing.JTextField txt_ngayTraPhong;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_searchAccount;
    private javax.swing.JTextField txt_soNgayO;
    private javax.swing.JTextField txt_soPhong;
    private javax.swing.JTextField txt_tenKhachHang;
    private javax.swing.JTextField txt_tongTien;
    // End of variables declaration//GEN-END:variables
}
