package form_hotel;


import javax.swing.JOptionPane;
import java.sql.*;
import project.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class forgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotPassword
     */
    public forgotPassword() {
        initComponents();
    }
    String email ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_Thoat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cauHoiBaoMat = new javax.swing.JTextField();
        txt_cauTraLoi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_matKhauMoi = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        lb_troLai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(424, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Thoat.setBackground(new java.awt.Color(255, 255, 255));
        lb_Thoat.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_Thoat.setText("x");
        lb_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 40));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quên mật khẩu ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 78, 230, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 24));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Câu hỏi bảo mật *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 24));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Câu trả lời *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 24));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mật khẩu mới *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, 24));

        txt_cauHoiBaoMat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txt_cauHoiBaoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 220, 24));

        txt_cauTraLoi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txt_cauTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 220, 24));

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Lưu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 24));

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Đăng ký");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 24));

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Đăng nhập");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, 24));
        jPanel1.add(txt_matKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 220, 24));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\search_24px.png")); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 0, -1, 24));

        txt_search.setForeground(new java.awt.Color(255, 0, 51));
        txt_search.setBorder(null);
        jPanel5.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 24));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 24));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 470));

        lb_troLai.setBackground(new java.awt.Color(255, 255, 255));
        lb_troLai.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb_troLai.setForeground(new java.awt.Color(255, 255, 255));
        lb_troLai.setText(" <");
        lb_troLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_troLaiMouseClicked(evt);
            }
        });
        getContentPane().add(lb_troLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\hotel2.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        String security = txt_cauHoiBaoMat.getText();
        String answer = txt_cauTraLoi.getText();
        String newPassword = txt_matKhauMoi.getText();
        if(answer.equals("")|| newPassword.equals(""))
        {
            check = 1;
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập đầy đủ thông tin");
        }
        else 
        {
            ResultSet rs = Select .getData("select * from users where email='"+email+"' and securityQuestion = '"+security+"' and answer = '"+answer+"'");
            try {
                if(rs.next())
                {
                    check=1;
                    InsertUpdateDelete.setData("update users set password = '"+newPassword+"' where email = '"+email+"'","Change password succesfull");
                    setVisible(false);
                    new forgotPassword().setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(check==0)
            JOptionPane.showMessageDialog(null, "Câu trả lời không đúng");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new signup().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lb_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0)
        {
            setVisible(false);
              System.exit(a);
        }
    }//GEN-LAST:event_lb_ThoatMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
       int check = 0;
        email = txt_search.getText();
        if(email.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Email không được bỏ trống");
        }
        else 
        {
            ResultSet rs = Select.getData("select * from users where email='"+email+"'");
            try {
                if(rs.next())
                {
                    check = 1;
                    txt_cauHoiBaoMat.setEditable(false);
                    txt_search.setEditable(false);
                    txt_cauHoiBaoMat.setText(rs.getString(4));
                }
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
            }
            if(check ==0)
            {
                    JOptionPane.showMessageDialog(null,"Email khong chinh xac");
            }
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void lb_troLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_troLaiMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_lb_troLaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_Thoat;
    private javax.swing.JLabel lb_troLai;
    private javax.swing.JTextField txt_cauHoiBaoMat;
    private javax.swing.JTextField txt_cauTraLoi;
    private javax.swing.JPasswordField txt_matKhauMoi;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
