package form_hotel;

import java.awt.Image;
import project.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        txt_ngayDatPhong.setEditable(false);
        txt_Gia2.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        txt_ngayDatPhong.setText(myFormat.format(cal.getTime()));
    }
    String bed;
    String roomType;
    String roomNumber;
    String price;

    public void roomDetails() {
        cb_soPhong2.removeAllItems();
        txt_Gia2.setText("");
        bed = (String) cb_loaiGiuong2.getSelectedItem();
        roomType = (String) cb_loaiPhong2.getSelectedItem();
        try {
            ResultSet rs = Select.getData("select *from room where bed = '" + bed + "' and roomType = '" + roomType + "' and status ='Hoạt động'");
            while (rs.next()) {
                cb_soPhong2.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void validatePhoneNumber(String phoneNumber) {
        String regex = "\\d{10}"; // Chuỗi regex để kiểm tra số điện thoại có đúng định dạng không
        if (!phoneNumber.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txt_Gia.requestFocus();
            txt_Gia.selectAll();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tbp_user = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_soPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_loaiPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_kieuGiuong = new javax.swing.JComboBox<>();
        txt_Gia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_danhSachPhong = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lb_Search = new javax.swing.JLabel();
        txt_Search = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_ThoatTab1 = new javax.swing.JLabel();
        lb_anhNen2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tenKhachHang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Sdt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_quocTich = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_MCMND = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_ngayDatPhong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_Gia2 = new javax.swing.JTextField();
        btn_datPhong = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        cb_gioiTinh = new javax.swing.JComboBox<>();
        cb_loaiPhong2 = new javax.swing.JComboBox<>();
        cb_loaiGiuong2 = new javax.swing.JComboBox<>();
        cb_soPhong2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        lb_ThoatTab2 = new javax.swing.JLabel();
        lb_anhNen3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setMinimumSize(new java.awt.Dimension(980, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(980, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Số phòng *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 289, -1));

        txt_soPhong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_soPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 289, 27));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loại phòng *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 289, 30));

        cb_loaiPhong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_loaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng đơn", "Phòng đôi", "Phòng Vip" }));
        jPanel1.add(cb_loaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 289, 27));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kiểu giường *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 289, -1));

        cb_kieuGiuong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_kieuGiuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi", "Giường Vip" }));
        jPanel1.add(cb_kieuGiuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 290, 27));

        txt_Gia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_Gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 289, 27));

        tb_danhSachPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Giường", "Giá", "hình ảnh", "Trạng thái"
            }
        ));
        tb_danhSachPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_danhSachPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_danhSachPhong);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 510, 540));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Search.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\search_24px.png")); // NOI18N
        lb_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SearchMouseClicked(evt);
            }
        });
        jPanel5.add(lb_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 30));

        txt_Search.setForeground(new java.awt.Color(255, 0, 51));
        txt_Search.setBorder(null);
        jPanel5.add(txt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 310, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        jLabel21.setText("Khách Sạn Hương Ngọc Thảo");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 350, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giá / ngày*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 289, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, -1));

        lb_ThoatTab1.setBackground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab1.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_ThoatTab1.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab1.setText("x");
        lb_ThoatTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatTab1MouseClicked(evt);
            }
        });
        jPanel1.add(lb_ThoatTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 40));

        lb_anhNen2.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\qtv_1.jpg")); // NOI18N
        jPanel1.add(lb_anhNen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Tbp_user.addTab("Tìm phòng", jPanel1);

        jPanel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(980, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên khách hàng *");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, 30));

        txt_tenKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_tenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 230, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số điện thoại *");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, 30));

        txt_Sdt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_Sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SdtActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 230, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quốc tịch *");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 230, 30));

        txt_quocTich.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_quocTich, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 230, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Giới tính *");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 230, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email *");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 230, 30));

        txt_Email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 230, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mã CMND *");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 230, 30));

        txt_MCMND.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_MCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MCMNDActionPerformed(evt);
            }
        });
        jPanel2.add(txt_MCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 230, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Địa chỉ *");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 230, 30));

        txt_diaChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 230, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ngày đặt phòng *");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 230, 30));

        txt_ngayDatPhong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_ngayDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 230, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Số phòng *");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 230, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Loại phòng *");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 230, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Giường *");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 230, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Giá *");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 230, 30));

        txt_Gia2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_Gia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Gia2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Gia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 230, 30));

        btn_datPhong.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        btn_datPhong.setForeground(new java.awt.Color(255, 0, 51));
        btn_datPhong.setText("Đặt phòng");
        btn_datPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datPhongActionPerformed(evt);
            }
        });
        jPanel2.add(btn_datPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 120, 30));

        btn_lamMoi.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        btn_lamMoi.setForeground(new java.awt.Color(0, 153, 153));
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_lamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 120, 30));

        cb_gioiTinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam\t", "Nữ ", "Khác\t" }));
        jPanel2.add(cb_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 230, 30));

        cb_loaiPhong2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb_loaiPhong2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng đơn", "Phòng đôi", "Phòng Vip", " " }));
        cb_loaiPhong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loaiPhong2ActionPerformed(evt);
            }
        });
        jPanel2.add(cb_loaiPhong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 230, 30));

        cb_loaiGiuong2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb_loaiGiuong2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi", "Giường Vip" }));
        cb_loaiGiuong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loaiGiuong2ActionPerformed(evt);
            }
        });
        jPanel2.add(cb_loaiGiuong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 230, 30));

        cb_soPhong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_soPhong2ActionPerformed(evt);
            }
        });
        jPanel2.add(cb_soPhong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 230, 30));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 102));
        jLabel23.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        jLabel23.setText("Khách Sạn Hương Ngọc Thảo");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 390, -1));

        lb_ThoatTab2.setBackground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab2.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_ThoatTab2.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThoatTab2.setText("x");
        lb_ThoatTab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatTab2MouseClicked(evt);
            }
        });
        jPanel2.add(lb_ThoatTab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 40));

        lb_anhNen3.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\qtv_1.jpg")); // NOI18N
        jPanel2.add(lb_anhNen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Tbp_user.addTab("Đặt Phòng", jPanel2);
        Tbp_user.addTab("Liên hệ", jPanel3);

        getContentPane().add(Tbp_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("select * from room");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void txt_SdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SdtActionPerformed
        // TODO add your handling code here:
        String phoneNumber = txt_Gia.getText();
        validatePhoneNumber(phoneNumber);
    }//GEN-LAST:event_txt_SdtActionPerformed

    private void txt_MCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MCMNDActionPerformed

    private void txt_Gia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Gia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Gia2ActionPerformed

    private void btn_datPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datPhongActionPerformed
        // TODO add your handling code here:
        int id = 1;
        String name = txt_tenKhachHang.getText();
        String phoneNumber = txt_Sdt.getText();
        String nationality = txt_quocTich.getText();
        String gender = (String) cb_gioiTinh.getSelectedItem();
        String email = txt_Email.getText();
        String idProof = txt_MCMND.getText();
        String address = txt_diaChi.getText();
        String checkIn = txt_ngayDatPhong.getText();
        String bed = (String) cb_loaiGiuong2.getSelectedItem();
        String roomType = (String) cb_loaiPhong2.getSelectedItem();
        String roomNumber = (String) cb_soPhong2.getSelectedItem();
        String price = txt_Gia2.getText();

        String Query = "select max(id) from customer";
        if (name.equals("") || phoneNumber.equals("") || nationality.equals("") || email.equals("") || idProof.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần điền đầy đủ thông tin trước khi đặt phòng.");
        } else {
            int a = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đặt phòng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                try {
                    ResultSet rs = Select.getData(Query);
                    while (rs.next()) {
                        id = rs.getInt(1);
                        id = id + 1;

                        if (!price.equals("")) {
                            Query = "update room set status = 'Đóng cửa' where roomNumber = '" + roomNumber + "'";
                            InsertUpdateDelete.setData(Query, "");
                            Query = "insert into customer(id, name , phoneNumber, nationality, gender , email , idProof, address, checkIn, roomNumber, bed, roomType, pricePerDay) values(" + id + ", '" + name + "', '" + phoneNumber + "', '" + nationality + "', '" + gender + "', '" + email + "', '" + idProof + "','" + address + "', '" + checkIn + "', '" + roomNumber + "', '" + bed + "','" + roomType + "', '" + price + "')";
                            InsertUpdateDelete.setData(Query, " Bạn đặt phòng thành công !");
                            setVisible(false);
                            new home().setVisible(true);
                        }
                    }
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btn_datPhongActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);

    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void cb_loaiPhong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loaiPhong2ActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_cb_loaiPhong2ActionPerformed

    private void cb_loaiGiuong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loaiGiuong2ActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_cb_loaiGiuong2ActionPerformed

    private void cb_soPhong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_soPhong2ActionPerformed
        // TODO add your handling code here:
        roomNumber = (String) cb_soPhong2.getSelectedItem();
        try {
            ResultSet rs = Select.getData("select *from room where roomNumber = '" + roomNumber + "'");
            while (rs.next()) {
                txt_Gia2.setText(rs.getString(4));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cb_soPhong2ActionPerformed

    private void tb_danhSachPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_danhSachPhongMouseClicked
        // TODO add your handling code here:
        int row = tb_danhSachPhong.getSelectedRow();
        String RoomNumber = tb_danhSachPhong.getValueAt(row, 0).toString();
        String TypeRoom = tb_danhSachPhong.getValueAt(row, 1).toString();
        String Bed = tb_danhSachPhong.getValueAt(row, 2).toString();
        String Price = tb_danhSachPhong.getValueAt(row, 3).toString();
        String imgUrl = tb_danhSachPhong.getValueAt(row, 4).toString();
        String Status = tb_danhSachPhong.getValueAt(row, 5).toString();

        if (Status.toString().equals("Đóng cửa")) {
            JOptionPane.showMessageDialog(null, "Phòng " + RoomNumber + " hiện tại đang có người ở, Quý khách vui lòng chọn phòng khác !");
        } else {
            txt_soPhong.setText(RoomNumber);
            int i = 0;

            while (true) {
                String nameFromCbB = cb_loaiPhong.getItemAt(i).toString();
                if (nameFromCbB.equalsIgnoreCase(TypeRoom)) {
                    cb_loaiPhong.setSelectedIndex(i);
                    break;
                }
                i++;
            }

            while (true) {
                String nameFromCbB = cb_kieuGiuong.getItemAt(i).toString();
                if (nameFromCbB.equalsIgnoreCase(Bed)) {
                    cb_kieuGiuong.setSelectedIndex(i);
                    break;
                }
                i++;
            }

            txt_Gia.setText(Price + ".000 VND");
            new showroom(RoomNumber, TypeRoom, Bed, Price, imgUrl, Status).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tb_danhSachPhongMouseClicked

    private void lb_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SearchMouseClicked
        // TODO add your handling code here:
        String search = txt_Search.getText();
        ResultSet rs = Select.getData("select * from room where roomNumber = '" + search + "' or roomType like '" + search + "''%' ");
        DefaultTableModel model = (DefaultTableModel) tb_danhSachPhong.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lb_SearchMouseClicked

    private void lb_ThoatTab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatTab1MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            System.exit(a);
        }

    }//GEN-LAST:event_lb_ThoatTab1MouseClicked

    private void lb_ThoatTab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatTab2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            System.exit(a);
        }
    }//GEN-LAST:event_lb_ThoatTab2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tbp_user;
    private javax.swing.JButton btn_datPhong;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JComboBox<String> cb_gioiTinh;
    private javax.swing.JComboBox<String> cb_kieuGiuong;
    private javax.swing.JComboBox<String> cb_loaiGiuong2;
    private javax.swing.JComboBox<String> cb_loaiPhong;
    private javax.swing.JComboBox<String> cb_loaiPhong2;
    private javax.swing.JComboBox<String> cb_soPhong2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Search;
    private javax.swing.JLabel lb_ThoatTab1;
    private javax.swing.JLabel lb_ThoatTab2;
    private javax.swing.JLabel lb_anhNen2;
    private javax.swing.JLabel lb_anhNen3;
    private javax.swing.JTable tb_danhSachPhong;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Gia;
    private javax.swing.JTextField txt_Gia2;
    private javax.swing.JTextField txt_MCMND;
    private javax.swing.JTextField txt_Sdt;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_ngayDatPhong;
    private javax.swing.JTextField txt_quocTich;
    private javax.swing.JTextField txt_soPhong;
    private javax.swing.JTextField txt_tenKhachHang;
    // End of variables declaration//GEN-END:variables
}
