/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form_hotel;

import com.itextpdf.text.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.System.Logger.Level;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */




public class loading extends javax.swing.JFrame {

    /**
     * Creates new form loading
     */
    Timer thoiGian;
    public loading() {
        initComponents();
        Load();
        setLocationRelativeTo(null);
    }
     public void Load() {
        thoiGian = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                int giaTriHienTai = bar.getValue();
                giaTriHienTai = giaTriHienTai + 1;
                bar.setValue(giaTriHienTai);

                if (giaTriHienTai > 100) {
                    thoiGian.stop();
                    try {
                        new login().setVisible(true);
                    } catch (Throwable ex) {
                    }
                    dispose();
                }
            }
        });
        thoiGian.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_loGo = new javax.swing.JLabel();
        lb_title = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_loGo.setBackground(new java.awt.Color(255, 255, 255));
        lb_loGo.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        lb_loGo.setForeground(new java.awt.Color(255, 0, 51));
        lb_loGo.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        jPanel1.add(lb_loGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, 90));

        lb_title.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 0, 51));
        lb_title.setText("Wellcome Huong Ngoc Thao Hotel");
        jPanel1.add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 420, 50));

        bar.setBackground(new java.awt.Color(255, 255, 255));
        bar.setForeground(new java.awt.Color(0, 204, 204));
        bar.setStringPainted(true);
        jPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 370, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(635, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_loGo;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
