package form_hotel;

import form_hotel.home;
import form_hotel.forgotPassword;
import form_hotel.adminHome;
import javax.swing.JOptionPane;
import java.sql.*;
import project.Select;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JPasswordField();
        txt_Email = new javax.swing.JTextField();
        btn_dangNhap = new javax.swing.JButton();
        btn_dangKy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_Thoat = new javax.swing.JLabel();
        cb_matKhau = new javax.swing.JCheckBox();
        lb_quenMatKhau = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(424, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, 27));

        txt_matKhau.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 220, 27));

        txt_Email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, 27));

        btn_dangNhap.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_dangNhap.setForeground(new java.awt.Color(255, 51, 51));
        btn_dangNhap.setText("Đăng nhập");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 105, 27));

        btn_dangKy.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_dangKy.setForeground(new java.awt.Color(255, 51, 51));
        btn_dangKy.setText("Đăng ký");
        btn_dangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 100, 27));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\user_50px.png")); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 70, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\open_door_50px.png")); // NOI18N
        jLabel1.setText("Đăng nhập");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 70));

        lb_Thoat.setBackground(new java.awt.Color(255, 255, 255));
        lb_Thoat.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_Thoat.setText("x");
        lb_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 40));

        cb_matKhau.setBackground(new java.awt.Color(0, 153, 204));
        cb_matKhau.setForeground(new java.awt.Color(255, 255, 255));
        cb_matKhau.setText("Hiển thị mật khẩu ");
        cb_matKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_matKhauMouseClicked(evt);
            }
        });
        cb_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_matKhauActionPerformed(evt);
            }
        });
        jPanel1.add(cb_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 220, 40));

        lb_quenMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_quenMatKhau.setText("Quên mật khẩu ?");
        lb_quenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_quenMatKhauMouseClicked(evt);
            }
        });
        jPanel1.add(lb_quenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 470));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\icons8-hotel-64.png")); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\login.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed

        // TODO add your handling code here:
        int check = 0;
        String email = txt_Email.getText();
        String password = txt_matKhau.getText();
        if (email.equals("") || password.equals("")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "Email hoặc mật khẩu không được bỏ trống");
        } else if (email.equals("admin@gmail.com") && password.equals("admin102")) {
            check = 1;
            setVisible(false);
            new adminHome().setVisible(true);
        } else {
            ResultSet rs = Select.getData("select * from users where email = '" + email + "' and password ='" + password + "'");
            try {
                if (rs.next()) {
                    check = 1;
                    if (rs.getString(7).equals("true")) {
                        setVisible(false);
                        new home().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Chờ quản trị viên phê duyệt");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (check == 0) {
            JOptionPane.showMessageDialog(null, "Sai email hoặc mật khẩu");
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    private void btn_dangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangKyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_btn_dangKyActionPerformed

    private void lb_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            System.exit(a);
        }
    }//GEN-LAST:event_lb_ThoatMouseClicked

    private void cb_matKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_matKhauMouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_cb_matKhauMouseClicked

    private void cb_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_matKhauActionPerformed
        // TODO add your handling code here:
            if(cb_matKhau.isSelected())
            {
                txt_matKhau.setEchoChar((char)0);
            }
            else
            {
                txt_matKhau.setEchoChar('*');
            }
    }//GEN-LAST:event_cb_matKhauActionPerformed

    private void lb_quenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_quenMatKhauMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new forgotPassword().setVisible(true);
    }//GEN-LAST:event_lb_quenMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangKy;
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JCheckBox cb_matKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Thoat;
    private javax.swing.JLabel lb_quenMatKhau;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JPasswordField txt_matKhau;
    // End of variables declaration//GEN-END:variables
}
