package form_hotel;

import form_hotel.login;
import form_hotel.forgotPassword;
import javax.swing.JOptionPane;
import project.InsertUpdateDelete;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_dangKy = new javax.swing.JButton();
        txt_tenKhachHang = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_matKhau = new javax.swing.JPasswordField();
        txt_cauTraLoi = new javax.swing.JTextField();
        txt_diaChi = new javax.swing.JTextField();
        cb_cauHoiBaoMat = new javax.swing.JComboBox<>();
        btn_dangNhap = new javax.swing.JButton();
        btn_quenMatKhau = new javax.swing.JButton();
        lb_Thoat = new javax.swing.JLabel();
        lb_troLai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(840, 470));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(424, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đăng ký tài khoản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 20, -1, 50));

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Họ & tên *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 152, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mật khẩu *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Câu hỏi bảo mật *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Câu trả lời *");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Địa chỉ *");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 170, 20));

        btn_dangKy.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_dangKy.setText("Đăng Ký ");
        btn_dangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 24));

        txt_tenKhachHang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_tenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 270, 24));

        txt_Email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 270, 24));

        txt_matKhau.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 270, 24));

        txt_cauTraLoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_cauTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 270, 24));

        txt_diaChi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 270, 24));

        cb_cauHoiBaoMat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_cauHoiBaoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bạn thân nhất của bạn là ai ?", "Tên trường cấp 2 của bạn là gì ?", "Tên người yêu mối tình đầu của bạn là ai ?" }));
        jPanel1.add(cb_cauHoiBaoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 270, 24));

        btn_dangNhap.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_dangNhap.setText("Đăng Nhập");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 100, 24));

        btn_quenMatKhau.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_quenMatKhau.setForeground(new java.awt.Color(255, 0, 51));
        btn_quenMatKhau.setText("Quên Mật Khẩu ?");
        btn_quenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quenMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 410, 140, 24));

        lb_Thoat.setBackground(new java.awt.Color(255, 255, 255));
        lb_Thoat.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lb_Thoat.setText("x");
        lb_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ThoatMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 470));

        lb_troLai.setBackground(new java.awt.Color(255, 255, 255));
        lb_troLai.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb_troLai.setForeground(new java.awt.Color(255, 255, 255));
        lb_troLai.setText(" <");
        lb_troLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_troLaiMouseClicked(evt);
            }
        });
        getContentPane().add(lb_troLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\Java application\\Hotel Management System\\build\\classes\\img\\hotel2.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangKyActionPerformed
        // TODO add your handling code here:
        String name = txt_tenKhachHang.getText();
        String email = txt_Email.getText();
        String password = txt_matKhau.getText();
        String securityQuestion = (String) cb_cauHoiBaoMat.getSelectedItem();
        String answer = txt_cauTraLoi.getText();
        String address = txt_diaChi.getText();
        if (name.equals("") || email.equals("") || password.equals("") || answer.equals("") || address.equals(""))
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin trước khi đăng ký");
        else {
            String Query;
            Query = "insert into users values('" + name + "','" + email + "','" + password + "','" + securityQuestion + "','" + answer + "','" + address + "','false')";
            InsertUpdateDelete.setData(Query, "Đăng Ký tài khoản thành công ");
            setVisible(false);
            new signup().setVisible(true);
        }
    }//GEN-LAST:event_btn_dangKyActionPerformed

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    private void btn_quenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quenMatKhauActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new forgotPassword().setVisible(true);
    }//GEN-LAST:event_btn_quenMatKhauActionPerformed

    private void lb_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThoatMouseClicked
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng không ? ", "Thông báo !", JOptionPane.YES_NO_OPTION);
         if (a == 0)
         {
             setVisible(false);
               System.exit(a);
         }
    }//GEN-LAST:event_lb_ThoatMouseClicked

    private void lb_troLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_troLaiMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_lb_troLaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangKy;
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton btn_quenMatKhau;
    private javax.swing.JComboBox<String> cb_cauHoiBaoMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Thoat;
    private javax.swing.JLabel lb_troLai;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_cauTraLoi;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_tenKhachHang;
    // End of variables declaration//GEN-END:variables
}
